name: Ingest jobs

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch: {}

jobs:
  run-ingest:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Call ingestion endpoint
        run: |
          curl -sS "${{ secrets.VERCEL_INGEST_URL }}?secret=${{ secrets.CRON_SECRET }}"
